Add service to import data from remote URL vs uploading local file (#5406)
* add methods to import remote data from url

* copyright

* WIP: adding authentication to remote data request

* ENV VARS needs to be set a special way in the executor process environment

* allow negative IDs on osm read by ogr

* Submodule hoot-ui-2x cafbaa1ea..3718c4e74:
  > add ftp
  > remove unneeded
  > undo change not needed
  > add eye icon to hide/show pw
  > use a password field
  > add username/pw, make remote url a data type
  > Merge remote-tracking branch 'origin/hoot2x' into import_remote_data
  > Merge remote-tracking branch 'origin/hoot2x' into import_remote_data
  > add a URL input to import remote data

* manually set NONE translation to quick.js

full path may avoid this error:
ImportError: Import by filename is not supported.
Error running convert:
Unable to find an appropriate scripting language for: translations/quick.js

* Submodule hoot-ui-2x 3718c4e74..c2f24b3d7:
  > update build info
  > Merge remote-tracking branch 'origin/hoot2x' into import_remote_data
  > allow sftp and ftps